#simple php apache server with sync document root

services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    command: >
      sh -c "apt-get update && apt-get install -y curl git unzip && 
             curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
             apache2-foreground"